### PR TITLE
Feature: Add support for streaming data to mixins.apply_descrambler

### PR DESCRIPTION
**Pull request by krapes**
Add a try and except to handle cases where the stream_data json does not contain stream_data['player_response'])['streamingData']['formats']

### CODE REVIEW

**Comment by krapes** [comment]
This pull request merges a couple of fixes to the mixins.apply_descrambler. Specifically those from @giacaglia (this repo) and [FidoDidoVN](https://github.com/nficano/pytube/issues/467#issuecomment-568311609).

It also adds a try - except case for videos that were failing because they didn't have a _'formats'_ in the stream_data json

**Review by giacaglia — APPROVED** [review]
lgtm! 🚢 it

**Comment by krapes** [comment]
I dont think I have permissions to do the actual merge

**Comment by giacaglia** [comment]
Ok, I will do it! Thanks for the PR

**Pull request merged**
